build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.4
          compile_options: '--enable-gd --enable-openssl'
      tests:
        override:
          - php-scrutinizer-run

checks:
  php: true
